# Generated by Django 2.2.2 on 2019-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('camera', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('price', models.IntegerField()),
                ('display', models.TextField()),
                ('bluetooth', models.TextField()),
            ],
        ),
    ]
