# Generated by Django 2.2.2 on 2019-07-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_asus_samsung_xiaomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='apple', to='phones.Phone'),
        ),
        migrations.AddField(
            model_name='asus',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='asus', to='phones.Phone'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='samsung', to='phones.Phone'),
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='xiaomi', to='phones.Phone'),
        ),
    ]
