# Generated by Django 2.2.2 on 2019-07-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20190708_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='phone',
        ),
        migrations.AddField(
            model_name='samsung',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='samsung', to='phones.Phone'),
        ),
    ]
