# Generated by Django 2.2.2 on 2019-07-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_auto_20190708_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samsung',
            old_name='phone',
            new_name='telephone',
        ),
    ]
