# Generated by Django 2.2.2 on 2019-07-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_auto_20190708_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samsung',
            name='telephone',
        ),
        migrations.AddField(
            model_name='phone',
            name='samsung',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='phones.Samsung'),
        ),
    ]
