# Generated by Django 2.2.2 on 2019-07-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_auto_20190708_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='samsung',
        ),
        migrations.AddField(
            model_name='samsung',
            name='telephone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='samsung', to='phones.Phone'),
        ),
    ]
