# Generated by Django 2.1.1 on 2019-06-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190617_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='main',
            new_name='is_main',
        ),
    ]
