# Generated by Django 2.1.1 on 2019-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190617_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='is_main',
        ),
        migrations.AddField(
            model_name='scope',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалить?'),
        ),
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
