# Generated by Django 2.1.1 on 2019-06-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190617_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='is_deleted',
        ),
    ]
