# Generated by Django 2.1.1 on 2019-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_articlescope_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ManyToManyField(related_name='scope', through='articles.ArticleScope', to='articles.Article'),
        ),
    ]
