# Generated by Django 2.1.1 on 2019-06-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_scope_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='is_main',
        ),
    ]
