# Generated by Django 2.1.1 on 2019-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_articlescope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='article',
            new_name='articles',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
