# Generated by Django 2.1.1 on 2019-06-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20190618_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main', 'scope']},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
