# Generated by Django 2.2.3 on 2019-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
