# Generated by Django 2.2.3 on 2019-07-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='route_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
