# Generated by Django 2.2.3 on 2019-07-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_station_route_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='route_numbers',
        ),
    ]
